"""create users table

Revision ID: bb911d383b82
Revises: 47c3684930b7
Create Date: 2025-12-11 14:42:57.483170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb911d383b82'
down_revision: Union[str, None] = '47c3684930b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    "users",
    sa.Column("id", sa.Integer(), primary_key=True),
    sa.Column("email", sa.String(), nullable=False),
    sa.Column("full_name", sa.String(), nullable=True),
    sa.Column("is_active", sa.Boolean(), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
